import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "LevelUp - Game Finder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}
      >
        {/* Cabeçalho */}
        <header className="bg-blue-600 text-white py-4 shadow-lg">
          <div className="container mx-auto px-4 flex justify-between items-center">
            <h1 className="text-2xl font-bold">🎮 LevelUp</h1>
            <nav>
              <ul className="flex gap-4">
                <li>
                  <a href="/" className="hover:underline">
                    Home
                  </a>
                </li>
                <li>
                  <a href="#about" className="hover:underline">
                    Sobre
                  </a>
                </li>
                <li>
                  <a href="#contact" className="hover:underline">
                    Contato
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </header>

        {/* Conteúdo principal */}
        <main className="container mx-auto px-4 py-8">
          {children}
        </main>

        {/* Rodapé */}
        <footer className="bg-blue-600 text-white py-4 mt-8">
          <div className="container mx-auto px-4 text-center">
            <p>&copy; {new Date().getFullYear()} LevelUp. Todos os direitos reservados.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
