import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "LevelUp - Game Finder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-bg1 text-text1 flex flex-col min-h-screen`}
      >
        {/* Cabeçalho */}
        <header className="bg-primary text-white py-4 shadow-lg">
          <div className="container mx-auto px-4 flex justify-between items-center">
            <Image 
                src="/images/logo.png" 
                alt="Logo LevelUp" 
                width={150} 
                height={50} 
                className="w-[100px] h-auto" 
              />
            <nav>
              <ul className="flex gap-4">
                <li>
                  <a href="/">
                    Home
                  </a>
                </li>
                <li>
                  <a href="#about">
                    Sobre
                  </a>
                </li>
                <li>
                  <a href="#contact">
                    Contato
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </header>

        {/* Conteúdo principal */}
        <main className="container mx-auto px-4 py-8 flex-grow">
          {children}
        </main>

        {/* Rodapé */}
        <footer className="bg-primary text-white py-4 mt-8">
          <div className="container mx-auto px-4 text-center">
            <p>&copy; {new Date().getFullYear()} LevelUp. Todos os direitos reservados.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
